Add support for empty lists
renproject/pack pull request #6
Opened 2021-01-18 23:22 UTC by jazg

2021-01-18 23:26 UTC, loongy commented on list_test.go
> +var _ = FDescribe("List", func() {
@jazg you will need to remove this focus

2021-01-18 23:31 UTC, loongy requested changes

2021-01-18 23:31 UTC, loongy commented on list_test.go
> +var _ = FDescribe("List", func() {
```suggestion
var _ = Describe("List", func() {
```

2021-01-18 23:31 UTC, loongy commented on list_test.go
> -	})
We should keep these test cases, but explicitly check that they do *not* result in errors, but do result in Lists with the Nil element type.

2021-01-18 23:31 UTC, loongy commented on nil.go
> +}
Why does it wrap an existing empty struct? Why not:
```suggestion
// NewNil wraps an existing raw struct.
func NewNil() Nil {
	return Nil{}
}
```

2021-01-18 23:31 UTC, loongy commented on nil.go
> +	return x == y
```suggestion
	return true
```

2021-01-18 23:31 UTC, loongy commented on nil.go
> +	return x == y
Nil values are always equal to each other, because there is no "room" for variability.

2021-01-18 23:31 UTC, loongy commented on nil.go
> +	return reflect.ValueOf(NewNil(struct{}{}))
```suggestion
	return reflect.ValueOf(NewNil())
```

2021-01-18 23:31 UTC, loongy commented on nil_test.go
> +package pack
```suggestion
package pack_test
```
Some basic tests should be added.

2021-01-18 23:31 UTC, loongy commented on type.go
> +	value := Nil(struct{}{})
```suggestion
	value := Nil{}
```

2021-01-18 23:31 UTC, loongy commented on type.go
> +	value := Nil(struct{}{})
```suggestion
	value := Nil{}
```

2021-01-18 23:31 UTC, loongy commented on nil.go
> +}
Might be worth explicitly marshalling to/from JSON using the `nil` JSON value. That way we are able to distinguish between "not there" and "there, but nil".

2021-01-18 23:43 UTC, jazg commented on nil_test.go
> +package pack
This was just a draft PR :)

2021-01-18 23:53 UTC, loongy requested changes
Everything is looking good, but I found one bug (not with your changes, but made more obvious by your changes).

2021-01-18 23:53 UTC, loongy commented on list.go
> +		v.T = typeNil{}
This actually makes me realise there is a bug for the case when `len(v.Elems) > 0`. At the moment, the `v.T` would be left uninitialised, but it should be set to the type of `v.Elems[0]` and all elements should be checked to make sure they are consistent with that type.

2021-01-20 23:19 UTC, jazg commented
This PR is mostly complete but there are some open issues:
1. Struct binary marshal/unmarshal tests (previously didn't exist) are failing.
2. List JSON marshal/unmarshal tests (previously didn't exist) are failing.
3. We could introduce an `EncodeType` function and make use of it when handling empty lists in the `Encode` function, for a performance optimisation.

2021-01-21 05:48 UTC, loongy approved these changes

2021-01-21 05:48 UTC, merged